version = 1

test_coverage = [
  {
    "tool": "dotnet",
    "path": "MyApp/deepsource_report.xml"
  }
]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
