name: DeepSource
on: [push, pull_request]

jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run DeepSource analysis
      uses: deepsource-io/action@v1
      with:
        key: ${{ secrets.DEEPSOURCE_KEY }}
