name: Code Quality Check

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  analysis:  
    runs-on: ubuntu-latest  

    env:  
      DSN: ${{ secrets.DEEPSOURCE_DSN }}

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Install .NET SDK  
        uses: actions/setup-dotnet@v2  
        with:  
          dotnet-version: '8.x'  

      - name: Restore NuGet packages  
        run: dotnet restore MyApp/MyApp.csproj

      - name: Get DeepSource CLI  
        run: curl -s https://deepsource.io/cli | sh 

      - name: Build solution  
        run: dotnet build MyApp/MyApp.csproj --no-restore  

      - name: Execute tests  
        run: dotnet test MyApp/MyApp.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Perform DeepSource Analysis  
        run: ./bin/deepsource report --analyzer test-coverage --key csharp --value-file MyApp/deepsource_report.xml
